theme = "github"

[keys.normal]
D = ["extend_to_line_bounds", "delete_selection"]

[editor]
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
wrap-indicator = ""  # set wrap-indicator to "" to hide it

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "all"
nnbsp = "all"
newline = "none"

[editor.indent-guides]
render = true
character = "‚ñè"
skip-levels = 0

