#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "odrling"
email = "florianbadie@odrling.xyz"

[ui]
default-command = "log"
show-cryptographic-signatures = true

[signing]
behavior = "own"
backend = "gpg"
key = "9055EDDADC76E19A3820F9C22A82DB10234FF357"
