#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "odrling"
email = "florianbadie@odrling.xyz"

[ui]
default-command = "log"
show-cryptographic-signatures = true

[signing]
behavior = "own"
backend = "gpg"
key = "9055EDDADC76E19A3820F9C22A82DB10234FF357"

[templates]
log = "builtin_log_comfortable"

[aliases]
s = ["status"]
l = ["log", "-r", "all()", "-T", "builtin_log_oneline", "--no-graph"]
ll = ["log", "--git", "--stat"]
p = ["git", "push"]
push = ["git", "push"]
f = ["git", "fetch"]
fetch = ["git", "fetch"]
ro = ["rebase", "--onto"]
d = ["describe"]
bm = ["bookmark", "move"]
rebaseall = ["rebase", "-s", "roots(mutable())", "-d", "trunk()"]
ra = ["rebase", "-s", "roots(mutable())", "-d", "trunk()"]
